language: php

php:
 
  - 7.1.6

env:
  - DB=mysql

services:
  - memcached
  
before_script:
  - composer install
  

notifications:
  email: false
script: phpunit --configuration phpunit.xml --coverage-text