language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.1.6

env:
  - DB=mysql

services:
  - memcached
  
before_script:
  - composer install
  

notifications:
  email: false
script: phpunit --configuration phpunit.xml --coverage-text